### ISSUE TITLE
Provide A guide For Contribution

### ISSUE THREAD

**Issue by Mr-Sunglasses** [markusmobius/go-dateparser#1]
You can Provide a basic guide for adding language support like
 Dateparser - https://dateparser.readthedocs.io/en/latest/contributing.html

**Comment by RadhiFadlillah** [comment]
It has been added in [`42bad63`](https://github.com/markusmobius/go-dateparser/commit/42bad63f32f4ee65cf3deebd2ad8014c867c4940).
